# Generated by Django 5.2.13 on 2026-05-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка'), ('canceled', 'Отменен')], default='success', max_length=20, verbose_name='Статус'),
        ),
    ]
