# Generated by Django 5.2.13 on 2026-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор')], default='client', max_length=10, verbose_name='Роль'),
        ),
    ]
